name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the PUSH_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: sonnet-docs/package-lock.json

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Install dependencies
        run: |
          cd sonnet-docs
          npm ci

      - name: Build
        run: |
          cd sonnet-docs
          npm run build

      - name: Debug - List Directories
        run: |
          echo "Current directory structure:"
          pwd
          ls -la
          echo "sonnet-docs directory:"
          ls -la sonnet-docs
          echo "sonnet-docs/build directory:"
          ls -la sonnet-docs/build

      - name: Prepare artifact
        run: |
          echo "Checking for symlinks in build directory..."
          find sonnet-docs/build -type l -exec rm {} \;
          echo "Creating clean copy of build directory..."
          mkdir -p build_pages
          cp -rL sonnet-docs/build/* build_pages/
          echo "Listing contents of prepared directory..."
          ls -la build_pages

      - name: Debug - Verify Artifact Directory
        run: |
          echo "Verifying build_pages directory contents:"
          ls -la build_pages
          echo "Total files in build_pages:"
          find build_pages -type f | wc -l

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages
          path: build_pages

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3